### ISSUE TITLE
Team members page

### ISSUE THREAD

**Issue by iBeliever** [lirios/lirios.github.io#1]
Looks like elementary OS has a neat page that pulls team member details from Slack: https://github.com/elementary/website/blob/master/team.php

We'd either need to specify team members manually via templating or do it in JS if we want to integrate with Slack.

**Comment by Aldrog** [comment]
Once I designed a team members page for a project I took part in.
Look at the bottom of [this page](http://pm-map.ru).

Well, we're Liri and not Noodles Team :smile: but maybe you'll like some part of this one.

**Comment by tim-sueberkrueb** [comment]
Another idea would be to include our locations (maybe even in form of a map).

**Comment by plfiorini** [comment]
Meanwhile I added a temporary page with static data (that needs to be completed)

**Comment by plfiorini** [comment]
As per Slack conversation with @zigapk, we should replace the country because not everybody want this information to be of public domain. Timezone and Slack online status are enough to get in touch with people.
