### ISSUE TITLE
CSS doesn't load on Firefox

### ISSUE THREAD

**Issue by TheCom3di4n** [lirios/lirios.github.io#16]
Console output:
`TypeError(liri.io:23): document.body is null -> loadDeferredStyles()`

**Edit:** I found the error, a semicolon is missing.

**Comment by plfiorini** [comment]
Apparently that didn't fix the issue, the real problem is that at that point the body might not have been created yet so I moved the script inside body.

Another way could be to run the JS code in a load event.
