### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by plfiorini** [lirios/lirios.github.io#20]
Download page with links to Arch Linux packages, nightly images, stable images and sources.

**Comment by TheCom3di4n** [comment]
With `<li class="tab col s3 waves-effect">`, a waves effect can be added to the tabs. I would do it but I think that's a little bit scant for a pull request. :P

**Comment by plfiorini** [comment]
@TheCom3di4n done thanks

**Comment by plfiorini** [comment]
We need to fix Download on mobile

**Comment by TheCom3di4n** [comment]
@plfiorini What do you mean? Download page on mobile works fine for me!

**Comment by plfiorini** [comment]
@TheCom3di4n tabs are too small on my phone and the shell commands are scrollable because the size doesn;t fit
