### ISSUE TITLE
News highlights

### ISSUE THREAD

**Issue by plfiorini** [lirios/lirios.github.io#37]
Show last 3 news from the homepage

**Comment by ajkendal** [comment]
@plfiorini 

May I work on this issue?

**Comment by ajkendal** [comment]
@plfiorini 

Where do you want the news portion to be located? Are they redoing the layout in a different issue?

**Comment by plfiorini** [comment]
@ajkendal Nope the layout is not being reworked elsewhere. You can put the news between the white section with the bullet points and the footer.

**Comment by ajkendal** [comment]
@plfiorini 

Should this be closed? Or would you like me to rework the css and layout for the news feature ?

**Comment by plfiorini** [comment]
Yes we can close this issue @ajkendal
