### ISSUE TITLE
navigation not visible if the window width is exactly 1024 px

### ISSUE THREAD

**Issue by eyelash** [lirios/lirios.github.io#42]
if the window is wider than 1024px the navigation is visible and if the window is less than 1024 px wide there is the menu but if the window is exactly 1024 px wide there is no navigation at all.

![screenshot from 2017-03-28 21-21-53](https://cloud.githubusercontent.com/assets/2668288/24423450/444e323c-13fd-11e7-80b4-66adbf9c73b8.png)

**Comment by tim-sueberkrueb** [comment]
Thanks for reporting @eyelash, I can reproduce this.

**Comment by plfiorini** [comment]
Closed via #53
