### ISSUE TITLE
Adblock Plus breaks website look

### ISSUE THREAD

**Issue by IlyaBizyaev** [lirios/lirios.github.io#43]
Like, completely :)
![screenshot_20170425_124018](https://cloud.githubusercontent.com/assets/11175213/25376193/61f65900-29b4-11e7-88ba-32d9aa86aee6.png)

**Comment by Aldrog** [comment]
Can't reproduce neither in Chromium nor Firefox (default settings and filters).

**Comment by Luke123443** [comment]
Could you please post a screenshot of the console so we can see wich assets it is blocking? 

It's likely that your list is corrupted since it looks like it blocks mdl css/js

**Comment by IlyaBizyaev** [comment]
![spectacle aq7863](https://cloud.githubusercontent.com/assets/11175213/25376870/be3fb074-29b6-11e7-813e-d3d326b22cf0.png)
The problem seems to be a bit different: there is something else blocking assets, but in Chrome turning off ABP for liri.io helped.
In Firefox, that doesn't help; also, in Firefox on Android there's no Adblock and the problem is present.
<img src="https://cloud.githubusercontent.com/assets/11175213/25376970/20e866bc-29b7-11e7-9364-2d9ecb9877af.png" width="250">
The blocked resource is https://code.getmdl.io/1.3.0/material.red-orange.min.css, and https://code.getmdl.io is really not available.

**Comment by IlyaBizyaev** [comment]
...and now it is.
ABP was just a coincidence, it's something with timing. I already had this problem in the past, so probably https://code.getmdl.io/ is down at times.

**Comment by IlyaBizyaev** [comment]
Like, now again. Unstable server?

**Comment by Luke123443** [comment]
Now it looks like it's working, if i fetch this url(https://code.getmdl.io/1.3.0/material.red-orange.min.css) it works fine, this may be a problem of your location or something in your local area.

**Comment by IlyaBizyaev** [comment]
Yes, Opera uses VPN, so this file loads there.
Still no idea why this can happen. The connection is stable, all the other websites look as expected, and Russia doesn't seem to block design assets yet :)

**Comment by Luke123443** [comment]
Well that's a great question, but we can consider using [jscdn](https://cdnjs.com/libraries/material-design-lite) if it works better for users like you, though I don't have any problem(with both) here in Italy

**Comment by IlyaBizyaev** [comment]
Works. Is there a way to add it as a fallback so that it was used if https://code.getmdl.io/1.3.0/material.red-orange.min.css is not accessible?

**Comment by Luke123443** [comment]
Well, we could either change it(I don't think it would cause any problem) or watch when [those static scripts](https://github.com/lirios/lirios.github.io/blob/master/_layouts/base.html#L49-L56) and [these styles](https://github.com/lirios/lirios.github.io/blob/master/_layouts/base.html#L26-L32)(and [this one of curse](https://github.com/lirios/lirios.github.io/blob/master/_layouts/base.html#L11)) fail and try to load cdnjs ones. 
This shouldn't be too hard, tough I don't know what the others think.

/cc @pierremtb @plfiorini @tim-sueberkrueb

**Comment by emiliano1** [comment]
**It is the worse thing ever made.** Just making a developer's work harder to throw some simple css styling out there. I will not make a work around this because time = money, but I will put an alert on the website that "Ad Blocker Sucks!". The world does not need more developers, it need responsible developers that think outside the box. Blocking css is not any innovation and blocking terms like "ads" ain't rocket science.

**Comment by plfiorini** [comment]
I can use [https://cdnjs.com/libraries/material-design-lite](cdnjs), it doesn't take much time if I just replace the URL but I agree with @emiliano1 that we shouldn't spend development time trying to fix faulty ad-blockers.
