### ISSUE TITLE
Nightly images not in repo

### ISSUE THREAD

**Issue by guax** [lirios/lirios.github.io#47]
Tried to download the ISOs to test with a virtual machine and could not find the ISOs on the website.

![screenshot_2017-05-12_22-16-18](https://cloud.githubusercontent.com/assets/245491/26015272/aee70700-3760-11e7-8dcb-550e453cd0a0.png)

**Comment by terencode** [comment]
Looks like some they just did some cleanup, you should try again.
![image](https://cloud.githubusercontent.com/assets/12665563/26017961/7df2dc62-376c-11e7-87cf-89fb4267d304.png)

**Comment by guax** [comment]
Thanks @terencode!
