### ISSUE TITLE
Redo screenshots

### ISSUE THREAD

**Issue by plfiorini** [lirios/lirios.github.io#50]
Screenshots are old, update them

**Comment by Logan1x** [comment]
@plfiorini  Can i work on this Issue?

**Comment by Logan1x** [comment]
If yes then can you provide me screenshots ?

**Comment by plfiorini** [comment]
@Logan1x Yep to both, I just need some to make the screenshots and post them to this issue

**Comment by Logan1x** [comment]
what do you mean by 'some'? is it meant to be someone?

**Comment by plfiorini** [comment]
'some time'

**Comment by Logan1x** [comment]
Ok sure Take your time😊

**Comment by plfiorini** [comment]
![xwayland1](https://user-images.githubusercontent.com/843710/30962739-3eed7760-a44b-11e7-8087-d77e5d4d31b6.png)
![fluid-demo](https://user-images.githubusercontent.com/843710/30962772-61222358-a44b-11e7-9c14-177eb7cf2fdc.png)

**Comment by plfiorini** [comment]
![liri-apps1](https://user-images.githubusercontent.com/843710/30962915-e3b12d5a-a44b-11e7-9c0d-55ec10b12628.png)
![present-windows](https://user-images.githubusercontent.com/843710/30962953-fc4e6d14-a44b-11e7-9b8d-e48dad97bfd0.png)

**Comment by plfiorini** [comment]
Single apps (terminal) for their specific page:

![terminal1](https://user-images.githubusercontent.com/843710/30964100-3e1828bc-a450-11e7-8b35-dbd91bfb4d23.png)
![terminal2](https://user-images.githubusercontent.com/843710/30964101-3e1a151e-a450-11e7-82f0-8d79c82b82d2.png)

**Comment by plfiorini** [comment]
@Logan1x Here's the last bunch of pictures

![mediacontrols](https://user-images.githubusercontent.com/843710/30965024-1363215e-a454-11e7-8986-c682e404b3a6.png)
![mpv1](https://user-images.githubusercontent.com/843710/30965026-13656306-a454-11e7-9955-5372e55b5743.png)
![mpv2](https://user-images.githubusercontent.com/843710/30965025-136485e4-a454-11e7-85a3-8571e8f0e939.png)
![mpv3](https://user-images.githubusercontent.com/843710/30965028-136853c2-a454-11e7-9e13-126cc2482766.png)
![netcontrols](https://user-images.githubusercontent.com/843710/30965027-13661e7c-a454-11e7-8ff1-41c5c7492e6b.png)
![storagecontrols](https://user-images.githubusercontent.com/843710/30965029-136bcc1e-a454-11e7-8f39-2b182ec4ec71.png)

**Comment by danmcatee** [comment]
#51 Added some new screenshots

**Comment by Pratham567** [comment]
I am ready to assist in this??

**Comment by Logan1x** [comment]
I will need your assistance @Pratham567 🤗

**Comment by Logan1x** [comment]
@danmcatee  already added pr #51 Is this sufficient or you need anything else @plfiorini ?
