### ISSUE TITLE
Compile materialize.css from customized sass-libary

### ISSUE THREAD

**Issue by TheCom3di4n** [lirios/lirios.github.io#6]
I think a customized materialize.css-file makes the coding easier and prevents from components with unwanted colors.

You should take the red from the logo as primary and find a good secondary color, like a complementary color or a shadow color. I tried to but the logo files I have found have to many red grades, so you should take the color from the vector or a high quality png.

**Comment by zigapk** [comment]
@TheCom3di4n would you like to submit a pull request (now that we know our red is the default material red)? Otherwise I will do it when I have time. (And I would appreciate if you could just wait just a day or two, until I finish and push my work on feature/slack_team branch - to avoid merge conflicts).

**Comment by TheCom3di4n** [comment]
@zigapk Sure! Any suggestions for secondary color? Red/Red would be https://www.materialpalette.com/red/red.

This looks like:
![primary_secondary](https://cloud.githubusercontent.com/assets/22567618/19451890/e4b3d07a-94ae-11e6-80c2-4d8d5a7e6ba8.png)

If we take the same color for primary and secondary, it would looks like(...I know, there is not much difference...):
![primary_primary](https://cloud.githubusercontent.com/assets/22567618/19451947/34be180a-94af-11e6-80ae-311eaab7d2e0.png)

IMHO, the secondary looks better. I don't know if this would cause any conflicts with other colors but if so, the sass libary allows to change the color of every component.

**Comment by zigapk** [comment]
^ anyone with just a little sense of design?

**Comment by crutchcorn** [comment]
What are the specific color values of each?

**Comment by zigapk** [comment]
@TheCom3di4n my work on feature/slack_team is now merged to master, so you are good to submit your work via a pull request :)

**Comment by TheCom3di4n** [comment]
@zigapk Good! But I still don't know what I should use as secondary color. :sweat_smile:

**Comment by zigapk** [comment]
Use whichever you find better. We can allways replace it if we want, right? :)

**Comment by plfiorini** [comment]
@TheCom3di4n red/red makes sense i don't really see red to go along with the other material colors.

**Comment by plfiorini** [comment]
@TheCom3di4n maybe red and #d32f2f

**Comment by TheCom3di4n** [comment]
@plfiorini IMHO red/red looks better than red and #d32f2, there is not enough contrast between the two colors I think.

![red_ d32f2f](https://cloud.githubusercontent.com/assets/22567618/19762072/b664f9d8-9c38-11e6-938a-a1e17ab5d8e0.png)

I'm sorry, that I'm not a big help with the colors, I'm not really good at art stuff. :\

I pushed red/red, as @zigapk and I said, if there are any conflicts, we can easily change the colors! :) For futher adjustments, it's better to discuss things in a IRC or something I guess.
