### ISSUE TITLE
Change color theme according to the Logo

### ISSUE THREAD

**Issue by Udara-U3** [lirios/lirios.github.io#7]
Color theme should be changed to `#f4463a` or Logo should be changed to `Teal color`

![01](https://cloud.githubusercontent.com/assets/12265797/19407527/369a6322-92b6-11e6-8c6f-31850d14a664.jpg)

Also images should be matching with theme color

![02](https://cloud.githubusercontent.com/assets/12265797/19407536/6e159e34-92b6-11e6-878c-dbde701b0c68.jpg)

**Comment by zigapk** [comment]
@Udara-U3 was #f4463a extracted from the image? Because I thought it was the default red from material color palette, but I don't know for sure. @Aldrog @pierremtb @iBeliever @tim-sueberkrueb anybody knows for sure?

**Comment by Udara-U3** [comment]
@zigapk Yeah, Extracted from the Logo 😄

**Comment by Aldrog** [comment]
@Udara-U3 @zigapk `#f4463a` is **very** close to MD red (`#f44336`). Maybe it's just an encoding error?

**Comment by Udara-U3** [comment]
@zigapk @Aldrog It's not what I meant, check [this](http://liri.io/) currently website theme color is `Teal` color, I meant it should be changed according to the Logo color.

**Comment by zigapk** [comment]
Sure thing @Udara-U3 . I'm just looking for consistent red color and asked for that. However, using the default red everywhere would simplify everything a lot.

**Comment by TheCom3di4n** [comment]
Color theme would change with customized materialize.css from Issue #6.

> Extracted from the Logo

@Udara-U3 As I mentioned in #6, the logo has to many grades of red for a good extraction, the right color should be extracted from the vector.

**Comment by pierremtb** [comment]
I'm a bit late sorry. The background shape of the icon is #F44336 (Material Red 500).

**Comment by TheCom3di4n** [comment]
>The background shape of the icon is #F44336 (Material Red 500).

Thank you! Maybe, we should provide such information at the 'Contribute'-page or the 'Get Involved'-page.

**Comment by zigapk** [comment]
Great! @TheCom3di4n suggested to compile materialize.css from customizes sass-library in #6. However, I would rather just replace all teal classes in html code with red (takes a few seconds), but that is pure laziness :P

**Comment by crutchcorn** [comment]
That text is incredibly hard to read. We should stick to making things clear and legible

**Comment by TheCom3di4n** [comment]
> [...]but that is pure laziness

I'm a lazy person, too, but unfortunately, some of the components(...like badges...) can't be colorized with classes. :P
